services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    runtime: nvidia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - PLEX_CLAIM=claim-269yU8bN9o6uioMrs8Yc
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    ports:
      - "32400:32400/tcp"
      - "32469:32469/tcp"     # DLNA (optional)
    volumes:
      - /tank/containers/plex:/config
      - /tank/data/movies:/data/movies
      - /tank/data/tv:/data/tv
      - /tank/data/downloads/complete:/data/downloads
      - /dev/shm:/transcode