# =============================================
# Plex Media Server (linuxserver/plex)
#
# Service:
# - plex — Plex Media Server with optional NVIDIA GPU transcoding
# Docker Hub:
# - https://hub.docker.com/r/linuxserver/plex
# GitHub:
# - https://github.com/linuxserver/docker-plex
#
# Volumes:
# - /fileServerMountPath/containers/plex -> /config
# - /fileServerMountPath/data/movies -> /data/movies
# - /fileServerMountPath/data/tv -> /data/tv
# - /fileServerMountPath/data/downloads/complete -> /data/downloads
# - /dev/shm -> /transcode
# Ports:
# - 32400 (Plex web/UI)
# - 32469 (DLNA, optional)
#
# How to use:
# 1) Obtain a valid PLEX_CLAIM then start the container.
#    Set /fileServerMountPath to your Linux host path. On Docker Desktop with WSL,
#    use /mnt/<drive> (e.g., /mnt/d). Using local mounts simplifies RBAC/permissions.
# 2) Start:  docker compose up -d
# 3) Stop:   docker compose down
# 4) Update: docker compose pull && docker compose up -d
# =============================================
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    runtime: nvidia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - PLEX_CLAIM=claim-269yU8bN9o6uioMrs8Yc
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    ports:
      - "32400:32400/tcp"
      - "32469:32469/tcp"
    volumes:
      - /fileServerMountPath/containers/plex:/config
      - /fileServerMountPath/data/movies:/data/movies
      - /fileServerMountPath/data/tv:/data/tv
      - /fileServerMountPath/data/downloads/complete:/data/downloads
      - /dev/shm:/transcode