# =============================================
# n8n Automation Platform + PostgreSQL
#
# Services:
# - postgres (postgres:16) — PostgreSQL database backend for n8n
# - n8n (n8nio/n8n:latest) — n8n automation app and web UI
# Docker Hub:
# - https://hub.docker.com/_/postgres
# - https://hub.docker.com/r/n8nio/n8n
# GitHub:
# - https://github.com/n8n-io/n8n
#
# Volumes:
# - n8n-postgres -> /var/lib/postgresql/data
# - n8n-data -> /home/node/.n8n
#
# How to use:
# 1) Optionally switch named volumes to bind mounts for persistence under /fileServerMountPath (e.g., /mnt/<drive> on Docker Desktop/WSL).
# 2) Start:  docker compose up -d
# 3) Stop:   docker compose down
# 4) Update: docker compose pull && docker compose up -d
# 5) Access: http://localhost:5678 (default basic auth in env)
# =============================================
version: "3.9"

networks:
  n8n-net:
    driver: bridge

volumes:
  n8n-postgres:
  n8n-data:

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    volumes:
      - n8n-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports: ["5678:5678"]
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npass
      GENERIC_TIMEZONE: Australia/Brisbane
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: changeme
      N8N_ENCRYPTION_KEY: please-change-me
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_USER_FOLDER: /home/node/.n8n
      NODE_FUNCTION_ALLOW_EXTERNAL: "*"
      N8N_SECURE_COOKIE: false
    user: "1000:1000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - n8n-data:/home/node/.n8n
